_:
  @just -l

http-sock:
  echo "GET / HTTP/1.0\n" | nc -U /tmp/synth/backend.sock

_new-window NAME CMD:
  tmux new-w -t synth-os-back -n "{{NAME}}"
  tmux send-keys -t synth-os-back:"{{NAME}}" "{{CMD}}" ENTER

_new-tmux:
  tmux new -ds synth-os-back -n "README"
  tmux send-keys -t synth-os-back:README 'nv ./README.md "+set wrap"' ENTER
  @just _new-window "Edit" ""
  @just _new-window "Run" ""
  @just _new-window "Git" "git status"
  @just _new-window "Misc" ""

tmux:
  tmux has-session -t synth-os-back || just _new-tmux
  tmux a -t synth-os-back

watch:
  cargo leptos watch -P --hot-reload --js-minify true
